### ISSUE TITLE
Suddenly stopped working after nixos-23.11 release.

### ISSUE THREAD

**Issue by Animeshz** [nix-community/nixGL#149]
I recently updated my flake to point to `nixos-23.11`, and now nixGL wrapped apps have stopped working, here's an example:

```bash
$ kitty
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: iris
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[336 20:14:06.378865] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[336 20:14:06.378893] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

I'm not sure what caused it, I'll see if I can provide more information.

Few things I tried doesn't help, such as `LIBGL_ALWAYS_INDIRECT=1` removes initial repeated error, but last 2 lines remains.

My host is Void Linux, using nixGL along with home-manager. This started right after the nixpkgs flake update, I tried updating host and reboot as well, but no luck.

**Comment by nim65s** [comment]
Same for me (except s/iris/radeonsi), but only on i3 and not on sway.

**Comment by nim65s** [comment]
It is no longer broken for me: I can run both `kitty` & `nixGL kitty` from home-manager under both ubuntu 22.04 & Arch and both i3 & sway.

**Comment by Animeshz** [comment]
Apparantly it is still not fixed for me. I tried updating to latest nixpkgs pin.

Edit: its nixos-23.11 pin, will check with nixpkgs-unstable soon.
