### ISSUE TITLE
Don't include i686 binaries on non-x86 host architectures

### ISSUE THREAD

**Issue by rollcat** [nix-community/nixGL#150]
I've stumbled upon this blog post, describing a workaround for ARM machines: <https://artemis.sh/2023/12/19/nixgl-aarch64.html>

The post's author says:

> It would probably be good to fix this upstream, so that it doesn’t pull on i686 libraries on other architectures. I don’t actually know how to do that though, else I’d try to write a fix myself, so I’m writing about how to make it work right now since that’s what I’ve got the energy for.

I think raising this as an issue would be a good first step.

**Comment by SuperSandro2000** [comment]
Set this https://github.com/nix-community/nixGL/blob/main/nixGL.nix#L15 to false

**Comment by SuperSandro2000** [comment]
Please test #151
